import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from "next/font/google"; // Import the Inter font
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ToasterProvider } from "@/components/providers/toaster-provider";

// Import local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Import Inter font
const inter = Inter({
  subsets: ["latin"], // Specify the subsets you need
  variable: "--font-inter", // Optional: use a custom variable
});

// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout Component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}> 
          <ToasterProvider />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
